# Generated by Django 3.0.5 on 2020-04-20 16:06

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200419_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=profiles.models.get_default_profile_photo_path, upload_to=profiles.models.get_profile_photo_upload_path),
        ),
    ]
