# Generated by Django 3.0.2 on 2020-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='path',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
