# Generated by Django 3.0.2 on 2020-01-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_auto_20200129_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
