# Generated by Django 3.0.5 on 2020-04-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='value',
            new_name='percent',
        ),
    ]
