# Generated by Django 3.0.4 on 2020-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20200409_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/photos/default-avatar.jpg', upload_to='profiles/photos'),
        ),
    ]
