# Generated by Django 3.0.5 on 2020-04-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200405_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='file',
            new_name='filename',
        ),
    ]
