# Generated by Django 3.0.4 on 2020-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200324_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
