# Generated by Django 3.0.5 on 2020-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_login_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='gender'),
            preserve_default=False,
        ),
    ]
