# Generated by Django 3.0.5 on 2020-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='path',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
