# Generated by Django 3.0.5 on 2020-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200405_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
