# Generated by Django 3.0.5 on 2020-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='path',
        ),
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.CharField(default='', max_length=256),
        ),
    ]
