# Generated by Django 3.0.5 on 2020-04-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200405_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.CharField(default='lol', max_length=256),
        ),
    ]
