# Generated by Django 3.0.5 on 2020-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20200405_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='filename',
            field=models.CharField(max_length=256),
        ),
    ]
