# Generated by Django 3.0.2 on 2020-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('level', models.SmallIntegerField()),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
