# Generated by Django 3.0.2 on 2020-02-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
